services:
  db:
    image: ankane/pgvector
    ports:
      - 5435:5432
    volumes:
      - db:/data
    environment:
      - POSTGRES_PASSWORD=capix123
      - POSTGRES_USER=capi
      - POSTGRES_DB=capix

volumes:
  db:
